apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 41.6.0
# renovate: image=traefik
appVersion: v3.7.13
kubeVersion: '>=1.25.0-0'
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik-helm-chart
  - https://github.com/traefik/traefik
