apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production-pool
  namespace: metallb-system
spec:
  addresses:
    # A range of IPs available for MetalLB to assign
    # Make sure these IPs are not used by DHCP or other services on your network
    - 192.168.1.201/28
